# Generated by Django 5.2.5 on 2025-10-16 23:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accidente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('tipo', models.CharField(max_length=60)),
                ('gravedad', models.CharField(choices=[('LEVE', 'Leve'), ('MODERADA', 'Moderada'), ('GRAVE', 'Grave'), ('FATAL', 'Fatal')], max_length=10)),
                ('lugar', models.CharField(max_length=120)),
                ('hora_suceso', models.TimeField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True)),
                ('requiere_licencia', models.BooleanField(default=False)),
                ('dias_licencia', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(365)])),
                ('costo_estimado', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('reportado_a', models.CharField(blank=True, max_length=120)),
                ('observaciones', models.CharField(blank=True, max_length=255)),
                ('trabajadores_rut', models.CharField(blank=True, default='', help_text='RUTs involucrados separados por comas (ej: 11.111.111-1,22.222.222-2)', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='DesempenoTrabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trabajador_rut', models.CharField(max_length=12)),
                ('trabajador_nombre', models.CharField(max_length=60)),
                ('id_desempeno', models.IntegerField()),
                ('forma_de_hacer_trabajos', models.CharField(blank=True, max_length=255)),
                ('posibles_quejas', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='EficienciaTrabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trabajador_rut', models.CharField(max_length=12)),
                ('trabajador_nombre', models.CharField(max_length=60)),
                ('id_eficiencia', models.IntegerField()),
                ('trabajos_completados_en_1_mes', models.IntegerField(default=0)),
                ('sueldo_promedio_informado', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('nombre', models.CharField(max_length=60)),
                ('apellido', models.CharField(max_length=60)),
                ('fecha_nacimiento', models.DateField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('cargo', models.CharField(max_length=60)),
                ('area', models.CharField(blank=True, max_length=60)),
                ('tipo_contrato', models.CharField(choices=[('PLAZO_FIJO', 'Plazo fijo'), ('INDEFINIDO', 'Indefinido'), ('HONORARIOS', 'Honorarios')], max_length=20)),
                ('turno', models.CharField(choices=[('DIURNO', 'Diurno'), ('NOCTURNO', 'Nocturno'), ('ROTATIVO', 'Rotativo')], max_length=20)),
                ('fecha_ingreso', models.DateField()),
                ('sueldo_base', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo')], default='ACTIVO', max_length=10)),
                ('contacto_emergencia', models.CharField(blank=True, max_length=100)),
                ('telefono_emergencia', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trabajador_rut', models.CharField(blank=True, default='', help_text='RUT del trabajador', max_length=12)),
                ('trabajador_nombre', models.CharField(blank=True, default='', max_length=60)),
                ('trabajador_apellido', models.CharField(blank=True, default='', max_length=60)),
                ('fecha', models.DateField()),
                ('hora_entrada', models.TimeField(blank=True, null=True)),
                ('hora_salida', models.TimeField(blank=True, null=True)),
                ('minutos_atraso', models.PositiveIntegerField(default=0)),
                ('horas_extras', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('estado', models.CharField(choices=[('PRESENTE', 'Presente'), ('AUSENTE', 'Ausente'), ('LICENCIA', 'Licencia'), ('VACACIONES', 'Vacaciones')], max_length=12)),
                ('observaciones', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['-fecha'],
                'unique_together': {('trabajador_rut', 'fecha')},
            },
        ),
    ]
