# Generated by Django 5.2.5 on 2025-10-13 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accidente',
            name='trabajadores',
        ),
        migrations.AlterUniqueTogether(
            name='asistencia',
            unique_together={('trabajador_rut', 'fecha')},
        ),
        migrations.AddField(
            model_name='accidente',
            name='trabajadores_rut',
            field=models.CharField(blank=True, default='', help_text='RUTs involucrados separados por comas (ej: 11.111.111-1,22.222.222-2)', max_length=500),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='trabajador_apellido',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='trabajador_nombre',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='trabajador_rut',
            field=models.CharField(blank=True, default='', help_text='RUT del trabajador', max_length=12),
        ),
        migrations.RemoveField(
            model_name='asistencia',
            name='trabajador',
        ),
    ]
