# Generated by Django 5.2.5 on 2025-10-19 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SueldoTrabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trabajador_rut', models.CharField(max_length=12)),
                ('trabajador_nombre', models.CharField(max_length=60)),
                ('mes', models.CharField(help_text='Mes de cálculo (Ej: Octubre)', max_length=20)),
                ('cantidad_trabajos_mes', models.PositiveIntegerField(default=0, help_text='Número de trabajos realizados en el mes')),
                ('tipo_trabajos_mes', models.CharField(help_text='Descripción de los tipos de trabajos realizados', max_length=255)),
                ('sueldo_total_mes', models.DecimalField(decimal_places=2, default=0, help_text='Sueldo total correspondiente al mes', max_digits=12)),
            ],
        ),
    ]
