# Generated by Django 5.2.5 on 2025-10-13 01:22

# core/migrations/0002_remove_accidente_trabajador_and_more.py

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        # 1) Quitar primero el M2M de accidente (esto no afecta a Asistencia)
        migrations.RemoveField(
            model_name='accidente',
            name='trabajadores',
        ),

        # 2) AÑADIR los 3 nuevos campos en Asistencia
        migrations.AddField(
            model_name='asistencia',
            name='trabajador_apellido',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='trabajador_nombre',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='trabajador_rut',
            field=models.CharField(blank=True, default='', help_text='RUT del trabajador', max_length=12),
        ),

        # 3) AHORA sí: cambiar unique_together para usar trabajador_rut + fecha
        migrations.AlterUniqueTogether(
            name='asistencia',
            unique_together={('trabajador_rut', 'fecha')},
        ),

        # 4) Recién ahora eliminar el FK viejo
        migrations.RemoveField(
            model_name='asistencia',
            name='trabajador',
        ),

        # 5) Agregar el campo de ruts en Accidente
        migrations.AddField(
            model_name='accidente',
            name='trabajadores_rut',
            field=models.CharField(
                blank=True,
                default='',
                help_text='RUTs involucrados separados por comas (ej: 11.111.111-1,22.222.222-2)',
                max_length=500
            ),
        ),
    ]
