# Generated by Django 5.2.5 on 2025-10-20 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sueldotrabajador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sueldotrabajador',
            name='mes',
            field=models.CharField(help_text='Mes de cálculo', max_length=20),
        ),
    ]
