# Generated by Django 5.2.5 on 2025-10-16 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_accidente_trabajadores_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesempenoTrabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trabajador_rut', models.CharField(max_length=12)),
                ('trabajador_nombre', models.CharField(max_length=60)),
                ('id_desempeno', models.IntegerField()),
                ('forma_de_hacer_trabajos', models.CharField(blank=True, max_length=255)),
                ('posibles_quejas', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='EficienciaTrabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trabajador_rut', models.CharField(max_length=12)),
                ('trabajador_nombre', models.CharField(max_length=60)),
                ('id_eficiencia', models.IntegerField()),
                ('trabajos_completados_en_1_mes', models.IntegerField(default=0)),
                ('sueldo_promedio_informado', models.IntegerField(default=0)),
            ],
        ),
    ]
