# Generated by Django 5.2.5 on 2025-11-02 03:42

from django.db import migrations, models
import django.db.models.deletion

def forwards_fill_asistencia_trabajador(apps, schema_editor):
    Asistencia = apps.get_model('core', 'Asistencia')
    Trabajador = apps.get_model('core', 'Trabajador')

    # Backfill por RUT legado si existe
    for a in Asistencia.objects.all():
        if getattr(a, 'trabajador_id', None):
            continue
        rut = getattr(a, 'trabajador_rut', None)
        if rut:
            t = Trabajador.objects.filter(rut=rut).first()
            if t:
                a.trabajador = t
                a.save(update_fields=['trabajador'])

    # Fallback: si quedó algo sin asignar, usa el primer trabajador
    t_fallback = Trabajador.objects.order_by('id').first()
    if t_fallback:
        Asistencia.objects.filter(trabajador__isnull=True).update(trabajador=t_fallback)

def backwards_noop(apps, schema_editor):
    # No revertimos el backfill
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_sueldotrabajador_mes'),
    ]

    operations = [
        # 1) Modelo nuevo
        migrations.CreateModel(
            name='TipoTrabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol_cargo', models.CharField(max_length=60)),
                ('tipo_contrato', models.CharField(choices=[('PLAZO_FIJO', 'Plazo fijo'), ('INDEFINIDO', 'Indefinido'), ('HONORARIOS', 'Honorarios')], max_length=20)),
            ],
        ),

        # 2) Accidente: de texto a M2M
        migrations.RemoveField(
            model_name='accidente',
            name='trabajadores_rut',
        ),
        migrations.AddField(
            model_name='accidente',
            name='trabajadores',
            field=models.ManyToManyField(blank=True, related_name='accidentes', to='core.trabajador'),
        ),

        # 3) Trabajador: añadir FK a Tipo (nullable para evitar default=1)
        migrations.AddField(
            model_name='trabajador',
            name='tipo',
            field=models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='trabajadores', to='core.tipotrabajador'),
        ),
        # Remover campos antiguos sólo después de tener 'tipo'
        migrations.RemoveField(
            model_name='trabajador',
            name='cargo',
        ),
        migrations.RemoveField(
            model_name='trabajador',
            name='tipo_contrato',
        ),

        # 4) Asistencia: agregar FK 'trabajador' (nullable), luego backfill, luego NOT NULL
        migrations.AddField(
            model_name='asistencia',
            name='trabajador',
            field=models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='core.trabajador'),
        ),
        migrations.RunPython(forwards_fill_asistencia_trabajador, backwards_noop),
        migrations.AlterField(
            model_name='asistencia',
            name='trabajador',
            field=models.ForeignKey(null=False, blank=False, on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='core.trabajador'),
        ),
        # Ahora sí cambiamos unique_together
        migrations.AlterUniqueTogether(
            name='asistencia',
            unique_together={('trabajador', 'fecha')},
        ),
        # Remover los campos legados de Asistencia
        migrations.RemoveField(
            model_name='asistencia',
            name='trabajador_apellido',
        ),
        migrations.RemoveField(
            model_name='asistencia',
            name='trabajador_nombre',
        ),
        migrations.RemoveField(
            model_name='asistencia',
            name='trabajador_rut',
        ),

        # 5) Eficiencia y Desempeño: agregar FK (nullable) y quedarnos sin los textos
        migrations.AddField(
            model_name='desempenotrabajador',
            name='trabajador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='desempenos', to='core.trabajador'),
        ),
        migrations.RemoveField(
            model_name='desempenotrabajador',
            name='trabajador_nombre',
        ),
        migrations.RemoveField(
            model_name='desempenotrabajador',
            name='trabajador_rut',
        ),

        migrations.AddField(
            model_name='eficienciatrabajador',
            name='trabajador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eficiencias', to='core.trabajador'),
        ),
        migrations.RemoveField(
            model_name='eficienciatrabajador',
            name='trabajador_nombre',
        ),
        migrations.RemoveField(
            model_name='eficienciatrabajador',
            name='trabajador_rut',
        ),

        # 6) Sueldo: dejar FKs en nullable (ya lo tenías así)
        migrations.AddField(
            model_name='sueldotrabajador',
            name='eficiencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sueldos', to='core.eficienciatrabajador'),
        ),
        migrations.AddField(
            model_name='sueldotrabajador',
            name='trabajador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sueldos', to='core.trabajador'),
        ),
        migrations.AlterField(
            model_name='sueldotrabajador',
            name='cantidad_trabajos_mes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sueldotrabajador',
            name='sueldo_total_mes',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='sueldotrabajador',
            name='tipo_trabajos_mes',
            field=models.CharField(max_length=255),
        ),
    ]
