# Generated by Django 5.2.5 on 2025-11-02 01:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_drop_legacy_fields_and_constraints'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoTrabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol_cargo', models.CharField(max_length=60)),
                ('tipo_contrato', models.CharField(choices=[('PLAZO_FIJO', 'Plazo fijo'), ('INDEFINIDO', 'Indefinido'), ('HONORARIOS', 'Honorarios')], max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='trabajador',
            name='cargo',
        ),
        migrations.RemoveField(
            model_name='trabajador',
            name='tipo_contrato',
        ),
        migrations.AlterField(
            model_name='accidente',
            name='trabajadores',
            field=models.ManyToManyField(blank=True, related_name='accidentes', to='core.trabajador'),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='trabajador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='core.trabajador'),
        ),
        migrations.AlterField(
            model_name='desempenotrabajador',
            name='trabajador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desempenos', to='core.trabajador'),
        ),
        migrations.AlterField(
            model_name='eficienciatrabajador',
            name='trabajador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eficiencias', to='core.trabajador'),
        ),
        migrations.AlterField(
            model_name='sueldotrabajador',
            name='cantidad_trabajos_mes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sueldotrabajador',
            name='eficiencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sueldos', to='core.eficienciatrabajador'),
        ),
        migrations.AlterField(
            model_name='sueldotrabajador',
            name='sueldo_total_mes',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='sueldotrabajador',
            name='tipo_trabajos_mes',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='sueldotrabajador',
            name='trabajador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sueldos', to='core.trabajador'),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trabajadores', to='core.tipotrabajador'),
        ),
    ]
